version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: jaguar
      MYSQL_USER: unida123
      MYSQL_PASSWORD: unida123
    volumes:
      - C:\\Users\\user\\Desktop\\Codigos\\Cursopy\\clase5:/var/lib/mysql
    ports:
      - "3306:3306"

  python-app:
    build: ./app
    container_name: python-app-container
    volumes:
      - C:\\Users\\user\\Desktop\\Codigos\\Cursopy\\clase5\\app:/app
    ports:
      - "5001:5001"
    depends_on:
      - mysql
